### ISSUE TITLE
Add a README?

### ISSUE THREAD

**Issue by richb-hanover** [hawkinsw/goresponsiveness#3]
If I understand, this is a Go implementation of the RPM measurement from Apple. That's extremely cool.

Adding a README, even if brief, that tells a newcomer who's not familiar with Go how to run the program would be important.

And extra credit for a Dockerfile that means that I didn't have to install Go on my otherwise pristine laptop. (I try to follow the principles of [Run More Stuff in Docker](https://jonathan.bergknoff.com/journal/run-more-stuff-in-docker/))

Thanks!

**Comment by hawkinsw** [comment]
You got it!!

We are going to try to make a formal "announcement" of this soon, but for now I will definitely do both things! 

Thanks for your interest!!

Will

**Comment by hawkinsw** [comment]
@richb-hanover Let me know what you think about https://github.com/hawkinsw/goresponsiveness/commit/21c4e560d2033969317a7fc37b3ae6b1f6508292.

**Comment by richb-hanover** [comment]
Excellent! A couple fussy points:

* s/Monterrey/Monterey/g
* s/conducat/conduct/
* It would be helpful to include a link to an existing RPM server - perhaps Apple's? That would enable people to test their installation against a known-working server.
* Any inclination to create a Dockerfile for this? I am becoming increasingly attracted to the [notion of running stuff in Docker](https://jonathan.bergknoff.com/journal/run-more-stuff-in-docker/) to avoid installing a host of programming languages with an assortment of versions on my daily driver laptop.

Thanks!

**Comment by hawkinsw** [comment]
Thanks for the feedback! Typos are now fixed. https://github.com/hawkinsw/goresponsiveness/commit/75ccf8f64787831a14d0211a605636c34deef489

I have a link to a server implementation that you can use for testing but will definitely add a link for an Apple server so people can get started quickly. 

I am going to leave Docker for "future work" but definitely plan on doing it. If you'd like to help with that, it'd be great! Thanks again for the feedback!

Will

**Comment by richb-hanover** [comment]
OK... I haven't figured out a good address for a RPM server to test the implementation. Could you give a hint? Thanks.

**Comment by hawkinsw** [comment]
> OK... I haven't figured out a good address for a RPM server to test the implementation. Could you give a hint? Thanks.

You are in luck -- I just finished debugging support for testing against the Apple infrastructure. `pull` the latest code, rebuild and let me know what you think! (see README.md for how to run to test against the Apple servers). 

I would love to hear if/how it works for you! I am going to close this ticket, but please open another if you have any trouble -- that'll make it easier to track individual bugs.

Thanks for your interest/help!
Will
