### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by richb-hanover** [hawkinsw/goresponsiveness#5]
Thanks for providing the sample options for networkQuality.go. I got it (sort of) working - see #4 for those details.

The parameters described in the README seem to be missing a "--" in front of options, though. I'll keep adding to this issue if I have other observations. Thanks!

**Comment by hawkinsw** [comment]
What's interesting is that go's built-in argument parser will handle both `-` and `--`. Let me know if that matches what you are seeing.

**Comment by richb-hanover** [comment]
Yes - I think you're right: both `-` and `--` seem to work.
