### ISSUE TITLE
lbc/lbc.go:27:2: missing go.sum entry

### ISSUE THREAD

**Issue by richb-hanover** [hawkinsw/goresponsiveness#6]
I'm a newcomer to `go` so I don't have a lot of native knowledge about how to fix this. Running on macOS 10.15.7, go version go1.17.3 darwin/amd64 .

- `git clone https://github.com/hawkinsw/goresponsiveness.git hawkinsgorpm` 
- `cd hawkinsgorpm`
- `go build networkQuality.go` 

gives this error message. What other information could I provide? Thanks!

```
√ hawkinsgorpm % go build networkQuality.go
lbc/lbc.go:27:2: missing go.sum entry for module providing package golang.org/x/net/http2 (imported by github.com/hawkinsw/goresponsiveness/lbc); to add:
	go get github.com/hawkinsw/goresponsiveness/lbc
```

**Comment by richb-hanover** [comment]
**Update:** I realized that the last line was actually a hint... Running that command makes it work (see below).

Question: why didn't a pull of the entire repo get that file/those files? Thanks!

```
√ hawkinsgorpm % go get github.com/hawkinsw/goresponsiveness/lbc
go: downloading golang.org/x/net v0.0.0-20220225172249-27dd8689420f
go: downloading golang.org/x/text v0.3.7

√ hawkinsgorpm % go build networkQuality.go

√ hawkinsgorpm % ./networkQuality --config mensura.cdn-apple.com --port 443 --path /api/v1/gm/config
Download: 3.308422 MBps (26.467377 Mbps), using 12 parallel connections.
Upload: 3.003906 MBps (24.031250 Mbps), using 28 parallel connections.
Error occurred calculating RPM -- no probe measurements received.

```

**Comment by hawkinsw** [comment]
I think that what I just committed will make the building easier. Thanks for pointing out the problem to me. I am going to update the README.md as well.
